### PR TITLE
Adds Qml, Tauri and Dioxus

### PR DESCRIPTION
**Pull request by MoAlyousef**
Hello
This PR adds 3 more toolkits. Addresses:
#7 #26 #12

### CODE REVIEW

**Comment by IronOxidizer** [comment]
The Tauri example seems quite complicated for a "hello world" window. Is there any way to simplify it (I've never used Tauri)

**Comment by MoAlyousef** [comment]
I've tried to further minimize the tauri example. The tauri.conf.json is required, so is the icons/icon.png. It also requires that the ui be in its own path, I tried inlining the html but it wouldn't have it. 
I've removed the unnecessary deps that are auto-generated by the `cargo tauri init` command. I've also removed some unnecessary data from the tauri.conf.json.

**Comment by IronOxidizer** [comment]
Great, one more thing. I noticed the Dioxus bench doesn't have a size defined. Is that intentional? How does it set the size to 512x512?

**Comment by MoAlyousef** [comment]
I think it set 's the size of the window automatically. It has a WindowBuilder function that I could probably use. I'll try to specify the size of the window in the example.

**Comment by IronOxidizer** [comment]
Looks good! Thanks for adding these!

**Comment by IronOxidizer** [comment]
Looks like the QML window app starts, however there's no content. Mind taking a look? In the meantime, I'll update the results in an hour.

**Comment by MoAlyousef** [comment]
I’ll try to debug this soon. I have Qt installed on windows, but I’m trying to set it up for wsl for the benchmarks. It might be a missing component or it might require setting an app attribute like app->setAttribute(Qt::AA_UseDesktopOpenGL) for some devices or even software opengl. 
Unfortunately wsl is kinda limited. It won’t support higher versions of Opengl, so I can’t even run iced or egui apps. It makes issues harder to pinpoint.

**Comment by MoAlyousef** [comment]
I changed some settings in my xcsrv env and it appears correctly:
image

Even without `QApplication::setAttribute(Qt::AA_UseDesktopOpenGL); // or QApplication::setAttribute(Qt::AA_UseSoftwareOpenGL);`

**Comment by IronOxidizer** [comment]
I'm thinking it might be related to QML not properly supporting x11 network transparency? https://forum.qt.io/topic/112776/qml-window-is-always-empty/13

I was able to get it working when running it on the host, but when running in docker, I just get a blank screen.

**Comment by IronOxidizer** [comment]
Found another example of this issue here: https://stackoverflow.com/questions/52501594/qt-app-ui-elements-randomly-rendered-as-blank-black-in-docker

**Comment by IronOxidizer** [comment]
Was able to fix it by setting the IPC mode to "host"

**Pull request merged**
