### PR TITLE
add wxwidgets

### PR DESCRIPTION
**Pull request by MoAlyousef**
Hello
This PR adds wxwidgets. It also replaces some *-dev dependencies from iced/egui/imgui-rs.

### CODE REVIEW

**Comment by IronOxidizer** [comment]
Looks great! Will update results later tonight

**Comment by IronOxidizer** [comment]
Updated the results. For some reason, egui requires `libgtk-3-dev`, otherwise I get the following error: https://github.com/emilk/egui/issues/2689

**Comment by IronOxidizer** [comment]
I cut a new ticket to track this here: https://github.com/emilk/egui/issues/3174

**Comment by MoAlyousef** [comment]
Thank you
Regarding the libgtk-dev, I thought egui needed it for rfd support in the file_dialog example. Sorry for the broken build. 
The issue should clarify things.

**Pull request merged**
