### PR TITLE
remove libfltk1.3-dev from FLTK's bench.dockerfile

### PR DESCRIPTION
**Pull request by MoAlyousef**
This was added by mistake to the bench.dockerfile, it shouldn't be needed, and it just increases the image's size with needless header files.

### CODE REVIEW

**Comment by IronOxidizer** [comment]
That package is needed, otherwise I get the error along the lines of `Missing shared library libfltk.so.1.3`

**Comment by MoAlyousef** [comment]
That’s strange!
I’ll close the PR. If I figure something out I’ll create a new PR.

**Comment by IronOxidizer** [comment]
From what I can tell, fltk-rs is statically linking against fltk. That's part of why the binary is larger.

Fltk (C++) does no such static linking so it's using the shared library.

**Comment by MoAlyousef** [comment]
Yes. Fltk-rs builds FLTK from source and statically links it. 
The C++ example uses the libfltk distributed by the distro. Perhaps just adding libfltk1.3 instead of libfltk1.3-dev package would fix the build. From the debian site, it seems libfltk1.3 also distributes the shared library.

**Comment by IronOxidizer** [comment]
Yup, that was it. Made a commit to fix that and update the results.

Though its weird, I don't remember seeing a non `-dev` package for libfltk1.3, which is why I added libfltk1.3-dev.

**Pull request closed without merging**
